name: CI

on:
  push:
    # filtering branches here prevents duplicate builds from pull_request and push
    branches:
      - main
      - "v*"
    # always run CI for tags
    tags:
      - "*"
  pull_request: {}

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v4
      - run: yarn install --frozen-lockfile --non-interactive

      - name: Lint Addon
        run: yarn lint
        working-directory: ember-async-data

      - name: Lint Test App
        run: yarn lint
        working-directory: test-app

  tests_linux:
    needs: lint
    name: "Tests: ubuntu (node@${{ matrix.node-version }})"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        node-version: ["14", "16", "18"]

    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --frozen-lockfile --non-interactive
      - run: ./node_modules/.bin/ember test
        working-directory: test-app

  tests_other:
    needs: lint
    name: "Tests: ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}-latest"
    timeout-minutes: 10

    strategy:
      matrix:
        os: [macOS, windows]

    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v4
      - run: yarn install --frozen-lockfile --non-interactive
      - run: ./node_modules/.bin/ember test
        working-directory: test-app

  tests_compat:
    needs: tests_linux
    name: "Tests: Ember compatibility (ember-source@${{ matrix.ember-version }})"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        ember-version:
          - "lts-3.28"
          - "lts-4.4"
          - "release"
          - "beta"
          - "canary"

    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v4
      - run: yarn install --frozen-lockfile --non-interactive
      - run: "./node_modules/.bin/ember try:one ember-${{ matrix.ember-version }}"
        working-directory: test-app

  tests_ts:
    needs: lint
    name: "Tests: TS ${{ matrix.ts-version }}"
    runs-on: ubuntu-latest
    continue-on-error: false
    strategy:
      matrix:
        ts-version: ["4.5", "4.6", "4.7", "next"]

    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v4
      - run: yarn install --frozen-lockfile --non-interactive
      - run: yarn add -D typescript@${{ matrix.ts-version }}
        working-directory: ember-async-data

      - run: yarn tsc --noEmit
        working-directory: ember-async-data

      - run: yarn tsc --noEmit --project type-tests
        working-directory: ember-async-data
